apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.9.0
  name: botkube-clusterrole
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
